version: "3"
services:
  bot:
    image: pyrolynx/i-stop-understand:latest
    build:
      context: .
    env_file: .env
    environment:
      - REDIS_HOST=redis
    links:
      - redis
  redis:
    image: redis:latest
    command: ["--appendonly", "yes"]
    volumes:
      - ./redis:/data
    ports:
      - "127.0.0.1:6379:6379"
