version: "3"
services:
  bot:
    image: pyrolynx:latest
    build:
      context: .
    env_file: .env
    environment:
      - REDIS_HOST=redis
    links:
      - redis
  redis:
    image: redis:latest
    command: ["--appendonly", "yes"]
    volumes:
      - ./redis:/data
